backend:
  name: git-gateway
  branch: main # Branch to update (change to master if applicable)

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Noticias" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields: # The fields for each document, usually in frontmatter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Entradilla (Lead)", name: "description", widget: "text"}
      - {label: "Autor", name: "author", widget: "string", default: "Cheito Díaz"}
      - {label: "Imagen Destacada", name: "image", widget: "image"}
      - {label: "Cuerpo del Artículo", name: "body", widget: "markdown"}
